---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: lightgbm
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  runPolicy: Serial
  triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: s2i-generic-data-science-notebook:2024.2
  source:
    git:
      uri: https://github.com/srikantt/rhods-custom-notebook-example.git
    contextDir: demo/custom-notebook-image
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-generic-data-science-notebook:2024.2
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: lightgbm:4.5.0
