apiVersion: image.openshift.io/v1
kind: ImageStreamTag
metadata:
  name: lightgbm:4.5.0
  annotations:
    opendatahub.io/notebook-python-dependencies: '[{"name":"Numpy","version":"2.0.2"},{"name":"Scipy","version":"1.13.1"},{"name":"LightGBM","version":"4.5"}]'
    opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.9"}]'
    argocd.argoproj.io/sync-wave: "2"
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/notebook-image: "true"
lookupPolicy:
  local: true
tag:
  name: "4.5.0"
  referencePolicy:
    type: Local
